### ISSUE TITLE
Blueprints are handled incorrectly

### ISSUE THREAD

**Issue by jkpe** [jkpe/home-assistant-rewrite-automations-ai#1]
Running convert-json-yaml.py adds unnecessary `trigger`, `condition` and `action` keys, this prevents blueprint automations from running.

```yaml
- id: '1714129386145'
  alias: Garage Garden Door Left Open Alert
  description: Notifies if the garage door leading to the garden is left open for
    over 2 minutes. Sends notifications repeatedly every 12 hours until the door is
    closed, unless bypass mode is enabled.
  trigger:
  condition:
  action:
  use_blueprint:
    path: Raukze/contact-sensor-left-open-notification.yaml
```
